import {
  Achievement,
  BlogPost,
  Certification,
  EducationItem,
  ExperienceItem,
  Project,
  ServiceItem,
  SkillCategory,
  TimelineItem,
} from '@/types';

export const siteConfig = {
  name: 'Md Minhaj',
  role: 'Cyber Security Researcher & Penetration Tester',
  roles: ['Cyber Security Researcher', 'Ethical Hacker', 'Penetration Tester', 'Security Researcher', 'Bug Bounty Hunter'],
  typingWords: [
    'Penetration Testing',
    'Web Security',
    'Red Team',
    'OSINT',
    'Digital Forensics',
    'Network Security',
    'Malware Analysis',
  ],
  email: 'pentester.minhaj@gmail.com',
  github: 'https://github.com/Md-Minhaj-darkness',
  linkedin: 'https://www.linkedin.com/in/md-minhaj-darkness/',
  twitter: 'https://x.com/MDMINHA17101032',
  discord: 'https://discord.com/users/1316397974338797580',
  resumeUrl: '/resume/resume.pdf',
  location: 'Remote / Worldwide',
  about: `I'm a Cybersecurity Researcher, Penetration Tester, and Digital Forensics Practitioner specializing in offensive security, vulnerability research, and incident investigation. My expertise includes web application security, malware analysis, incident response, Linux, networking, and secure software development.

I enjoy discovering vulnerabilities, analyzing digital evidence, building security tools, and sharing practical cybersecurity knowledge through technical content and online training. I believe continuous learning is the foundation of staying ahead in cybersecurity.
.`,
};

export const services: ServiceItem[] = [
  { id: 'MOD-01', title: 'Application Penetration Testing', status: 'ACTIVE' },
  { id: 'MOD-02', title: 'API Penetration Testing', status: 'ACTIVE' },
  { id: 'MOD-03', title: 'AI/LLM Application Penetration Testing', status: 'ACTIVE' },
  { id: 'MOD-04', title: 'Red Teaming & Adversary Simulation', status: 'ACTIVE' },
  { id: 'MOD-05', title: 'Governance, Risk & Compliance Advisory', status: 'ACTIVE' },
  { id: 'MOD-06', title: 'Training, Awareness & Community Engagement', status: 'ACTIVE' },
  { id: 'MOD-07', title: 'Security Monitoring & Data Protection', status: 'ACTIVE' },
  { id: 'MOD-08', title: 'Incident Response & Threat Management', status: 'ACTIVE' },
];

export const aboutHighlights = [
  { title: 'Ethical Hacking', desc: 'Authorized offensive testing to uncover exploitable weaknesses before attackers do.' },
  { title: 'Web App Security', desc: 'Deep focus on OWASP Top 10, business logic flaws, and modern web attack surfaces.' },
  { title: 'Vulnerability Assessment', desc: 'Structured methodology for identifying, validating, and prioritizing risk.' },
  { title: 'Penetration Testing', desc: 'End-to-end engagements: recon, exploitation, privilege escalation, reporting.' },
  { title: 'Secure Coding', desc: 'Building and reviewing code with a security-first mindset from the ground up.' },
  { title: 'Linux & Networking', desc: 'Comfortable at the command line, from packet captures to kernel-level detail.' },
  { title: 'Continuous Learning', desc: 'Always in a lab, a CTF, or a writeup — the field moves fast and so do I.' },
  { title: 'Digital Forensics', desc: 'Digital evidence acquisition, analysis, recovery, and cybercrime investigation using industry-standard forensic methodologies.' },
];

export const skillCategories: SkillCategory[] = [
  {
    title: 'Programming',
    icon: 'Code2',
    skills: [
      { name: 'Python', level: 90 },
      { name: 'Bash', level: 88 },
      { name: 'JavaScript', level: 78 },
      { name: 'PHP', level: 70 },
      { name: 'SQL', level: 80 },
    ],
  },
  {
    title: 'Operating Systems',
    icon: 'Terminal',
    skills: [
      { name: 'Kali Linux', level: 95 },
      { name: 'Ubuntu', level: 88 },
      { name: 'Windows', level: 82 },
    ],
  },
  {
    title: 'Security Domains',
    icon: 'ShieldHalf',
    skills: [
      { name: 'Web Pentesting', level: 92 },
      { name: 'API Security', level: 85 },
      { name: 'Network Security', level: 84 },
      { name: 'Active Directory', level: 75 },
      { name: 'OSINT', level: 86 },
      { name: 'Digital Forensics', level: 82 },
      { name: 'Malware Analysis', level: 72 },
      { name: 'Threat Hunting', level: 82 },
    ],
  },
  {
    title: 'Tools',
    icon: 'Wrench',
    skills: [
      { name: 'Burp Suite', level: 92 },
      { name: 'Nmap', level: 90 },
      { name: 'Metasploit', level: 82 },
      { name: 'Wireshark', level: 80 },
      { name: 'Nessus', level: 75 },
      { name: 'OWASP ZAP', level: 85 },
      { name: 'Hydra', level: 78 },
      { name: 'Gobuster', level: 88 },
      { name: 'ffuf', level: 85 },
      { name: 'SQLMap', level: 84 },
      { name: 'Nikto', level: 76 },
      { name: 'John the Ripper', level: 74 },
      { name: 'Hashcat', level: 74 },
      { name: 'BloodHound', level: 70 },
    ],
  },
];

export const projects: Project[] = [
  {
    id: 'proj-1',
    title: 'Subdomain Takeover Scanner',
    description:
      'A CLI tool that automates passive enumeration and CNAME fingerprinting to flag potentially vulnerable subdomains across large scopes.',
    image: '/images/projects/placeholder-1.svg',
    technologies: ['Python', 'DNS', 'Requests', 'Asyncio'],
    category: 'Tooling',
    section: 'Featured',
    github: 'https://github.com/yourusername/subtakeover-scanner',
    demo: '',
    date: '2026',
  },
  {
    id: 'proj-2',
    title: 'Web App Pentest Report — E-Commerce Client',
    description:
      'Full black-box assessment covering authentication flaws, IDOR, and stored XSS with a remediation-focused report.',
    image: '/images/projects/placeholder-2.svg',
    technologies: ['Burp Suite', 'OWASP Top 10', 'Manual Testing'],
    category: 'Web Pentest',
    section: 'Featured',
    github: '',
    demo: '',
    date: '2026',
  },
  {
    id: 'proj-3',
    title: 'Internal Network Segmentation Audit',
    description:
      'Simulated lateral movement inside a segmented lab environment to validate firewall rules and VLAN isolation.',
    image: '/images/projects/placeholder-3.svg',
    technologies: ['Nmap', 'Wireshark', 'pfSense'],
    category: 'Network Security',
    section: 'Labs',
    github: 'https://github.com/yourusername/network-seg-lab',
    date: '2025',
  },
  {
    id: 'proj-4',
    title: 'HTB — "Forest" Writeup',
    description:
      'Active Directory box exploited via anonymous LDAP bind, then privilege escalation through certificate services.',
    image: '/images/projects/placeholder-4.svg',
    technologies: ['Active Directory', 'BloodHound', 'Impacket'],
    category: 'Network Security',
    section: 'CTF Writeups',
    github: 'https://github.com/yourusername/htb-writeups',
    date: '2025',
  },
  {
    id: 'proj-5',
    title: 'OSINT Framework for Employee Footprinting',
    description:
      'Research project mapping open-source techniques for corporate attack-surface discovery via employee digital footprints.',
    image: '/images/projects/placeholder-5.svg',
    technologies: ['OSINT', 'Python', 'Recon-ng'],
    category: 'OSINT',
    section: 'Security Research',
    github: 'https://github.com/yourusername/osint-footprint',
    date: '2025',
  },
  {
    id: 'proj-6',
    title: 'ffuf Wordlist Contribution',
    description:
      'Contributed curated fuzzing wordlists and fixed edge-case bugs in a popular open-source fuzzing project.',
    image: '/images/projects/placeholder-6.svg',
    technologies: ['ffuf', 'Go', 'Wordlists'],
    category: 'Tooling',
    section: 'Open Source',
    github: 'https://github.com/yourusername/ffuf-contrib',
    date: '2025',
  },
];

export const projectSections = ['Featured', 'Labs', 'CTF Writeups', 'Security Research', 'Open Source'] as const;

export const achievements: Achievement[] = [
  { title: 'Hall of Fame & bug bounty', issuer: 'HackerOne', date: '2025', type: 'Bug Bounty' },
  { title: 'ACP Certified', issuer: 'APISEC', date: '2025', type: 'Certification' },
  { title: 'TryHackMe Lab Solve', issuer: 'TryHackMe', date: '2025', type: 'CTF' },
  { title: 'Hall of Fame', issuer: 'Bugcrowd', date: '2025', type: 'Bug Bounty' },
  { title: 'Hall of Fame', issuer: 'Self Host Program', date: '2025', type: 'Bug Bounty' },
  { title: 'Lab & CTF Solve', issuer: 'Root-me', date: '2024', type: 'CTF' },
];

export const learningJourney: TimelineItem[] = [
  { year: '2021', title: 'First Steps', description: 'Discovered ethical hacking through CTFs and started learning Linux fundamentals.' },
  { year: '2022', title: 'Foundations', description: 'Built networking and scripting fundamentals; completed first vulnerable-machine walkthroughs.' },
  { year: '2023', title: 'Specialization', description: 'Focused on web application security and started participating in bug bounty programs.' },
  { year: '2024', title: 'Certification & Community', description: 'Earned eJPT, began publishing writeups, and joined the local security community.' },
  { year: '2025', title: 'Professional Growth', description: 'Delivered first client pentest engagements and expanded into Active Directory attacks.' },
  { year: '2026', title: 'Today', description: 'Working toward OSCP while contributing to open-source security tooling.' },
];

export const experience: ExperienceItem[] = [
  {
    role: 'Bug Bounty Hunter',
    company: 'HackerOne Platform',
    duration: '2023 — Present',
    location: 'Remote',
    points: [
      'Conducted black-box and gray-box web application assessments on various programs via the HackerOne platform.',
      'Authored professional-grade findings reports with CVSS scoring and remediation guidance.',
      'Collaborated with blue team counterparts on detection validation post-engagement.',
    ],
  },
  {
    role: 'jr. Penetration Tester',
    company: 'bytecapsuleit',
    duration: '2024 — 2025',
    location: 'Hybrid',
    points: [
      'Researched emerging CVEs and reproduced proof-of-concept exploits in isolated lab environments.',
      'Built internal tooling to automate recon phases of engagements, cutting setup time significantly.',
    ],
  },
];

export const education: EducationItem[] = [
  {
    degree: 'Cyber Security',
    institution: 'Coursera / Udemy / Google / other online platforms',
    duration: '2022 — 2026',
    location: 'Online Learning',
    description: 'Focused coursework in network security, cryptography, and systems programming.',
  },
];

export const certifications: Certification[] = [
  { name: 'Ethical Hacking For Professionals', shortName: 'EHP', issuer: 'bytecapsuleit', status: 'Completed', year: '2025', color: '#00ff9c' },
  { name: 'APIsec Certified Practitioner', shortName: 'ACP', issuer: 'APISEC', status: 'Completed', year: '2025', color: '#00ff9c' },
  { name: 'Basic to Advanced Digital Forensics & Cyber Crime Investigation', shortName: 'DFIR', issuer: 'bytecapsuleit', status: 'Completed', year: '2025', color: '#00ff9c' },
  { name: 'Mastering Android Bug Bounties with Personal PoC', shortName: 'MABB', issuer: 'Udemy', status: 'Completed', year: '2025', color: '#00ff9c' },
  { name: 'Offensive Security Certified Professional', shortName: 'OSCP', issuer: 'Offensive Security', status: 'Future Goal', color: '#ffb800' },
  { name: 'Offensive API Exploitation', shortName: 'API Exploitation', issuer: 'Udemy', status: 'Completed', year: '2024', color: '#00ff9c' },
  { name: 'Practical Bug Bounty', shortName: 'PBB', issuer: 'TCM Security', status: 'Completed', year: '2023', color: '#00ff9c' },
  { name: 'Practical API Hacking', shortName: 'PAH', issuer: 'TCM Security', status: 'Completed', year: '2023', color: '#00ff9c' },
];

export const stats = [
  { label: 'Projects', value: 60 },
  { label: 'Labs Completed', value: 120 },
  { label: 'CTFs Played', value: 10 },
  { label: 'GitHub Contributions', value: 100 },
  { label: 'Certifications', value: 10 },
];

export const blogPosts: BlogPost[] = [
  {
    id: 'blog-1',
    title: 'Understanding IDOR: Hunting Tips and Techniques',
    excerpt: 'A practical look at how Insecure Direct Object References slip past code review and how to hunt for them systematically.',
    date: 'Jun 2026',
    readTime: '6 min read',
    tags: ['Web Security', 'OWASP'],
    slug: 'understanding-idor',
    content: [
    "Insecure Direct Object References (IDOR) remain one of the most common — and most overlooked — vulnerabilities in modern web applications. They happen when an application exposes a reference to an internal object, like a database ID, without properly verifying that the requesting user is actually authorized to access it.",
  "To understand IDOR, think of a hotel. Authentication is the front desk checking your ID and giving you a room key card. Authorization is making sure your key card only opens your assigned room, not the penthouse suite next door. An IDOR happens when the hotel door lets you in just because you changed the room number written on your card.",
  "## Why IDOR Slips Past Code Review",
  "Most IDOR bugs are not the result of bad code in isolation. They emerge from the gap between authentication (who you are) and authorization (what you are allowed to touch).",
  "When reviewing code, developers often check off a mental list: \"Is the user logged in? Yes. Is the session valid? Yes.\" Because the code looks secure on the surface, the bug slips through. The developer correctly verifies that a user is logged in, but completely forgets to check if the specific record being requested actually belongs to that user. In modern applications built on microservices and complex APIs, tracking data ownership across multiple database tables makes this even harder to spot during a manual code review.",
  "## A Systematic Hunting Approach",
  "To find IDOR vulnerabilities systematically, you must adopt a methodical testing workflow rather than randomly guessing numbers.",
  "1. **Map the Attack Surface:** Start by mapping every single endpoint that accepts an identifier. Look closely at API routes (/api/v1/orders/1024), query parameters (?invoice_id=9982), and request bodies. Identify user IDs, order numbers, invoice references, account settings, and file paths.",
  "2. **Establish Multi-Tenant Personas:** Set up at least two distinct user accounts with the exact same privilege levels (e.g., User A and User B, both standard customers).",
  "3. **The Swap Test:** Capture a request made by User A (for example, viewing User A's private profile). Change the identifier in that request to match User B's identifier.",
  "4. **Analyze the Response:** If User A can view or modify User B's data, you have successfully discovered an IDOR.",
  "> Tip: Pay special attention to feature additions. Endpoints added later in a project's life cycle are highly prone to IDORs because they are often rushed or bolted on without thoroughly integrating into the application's core authorization model.",
  "> Tip: Advanced IDOR hunting goes beyond simple parameter manipulation to exploit hidden API structures, state management flaws, and method tampering. Key hidden vectors include HPP, changing content types (JSON/XML), abusing leaked UUIDs, version downgrading (/v3/ to /v2/), and second-order IDORs where inputs are stored and executed later.",
  "## Practical Hunting Tips & Automation",
  "Hunting IDORs manually across hundreds of endpoints is exhausting. Modern bug hunters and penetration testers use smart automation to scale their efforts.",
  "**Automate with Burp Suite:** Capture a full authenticated session of User A using Burp Suite. Then, utilize extensions like Authorize or Match and Replace to automatically swap User A's session token/cookie with User B's session token on every outgoing request. Any request that still returns a 200 OK status code with actual data payload requires an immediate, closer look.",
  "**Look Beyond Sequential Integers:** While sequential IDs (1, 2, 3...) are the easiest to exploit, do not ignore UUIDs (Universally Unique Identifiers) or encoded strings (like Base64 hashes). If a UUID is leaked in a public forum, a comment section, or an unauthenticated API endpoint, it can still be used to trigger an IDOR if the backend lacks authorization checks.",
  "**Test All HTTP Methods:** An endpoint might be secure against unauthorized reading (GET), but completely vulnerable to unauthorized modification (PUT, POST, DELETE). Always check if you can delete or edit another user's resources.",
  "## Conclusion",
  "IDOR is incredibly simple to explain but remarkably easy to miss at scale. It requires no complex exploit payloads or memory corruption knowledge — just a fundamental understanding of how logic flows through an application. Treating authorization checks as a first-class concern, validated on every single object-returning endpoint, is the only reliable defense.",
    ],
  },
  {
    id: 'blog-2',
    title: 'My Subdomain Enumeration Methodology',
    excerpt: 'The passive and active recon workflow I use before touching a single endpoint during bug bounty hunting.',
    date: 'May 2026',
    readTime: '8 min read',
    tags: ['Recon', 'Bug Bounty'],
    slug: 'subdomain-enum-methodology',
     content: [
      "Subdomain enumeration is the process of finding valid subdomains for a target domain. It expands the attack surface and reveals hidden assets, staging environments, or forgotten portals. A robust methodology combines Passive and Active techniques.",
  "## Passive Subdomain Enumeration",
  "Passive enumeration gathers data from third-party sources without directly interacting with the target's infrastructure. This minimizes the risk of detection.",
  "**Certificate Transparency (CT) Logs** — Certificate Authorities (CAs) publicly log every SSL/TLS certificate issued. These logs are a goldmine for subdomains.",
  "1. `crt.sh` — a web-based interface to search CT logs.",
  "2. **Certspotter** — monitors CT logs in real-time.",
  "**Search Engine Scraping (Google Dorking)** — search engines index subdomains automatically. You can filter results to exclude the main domain using the operator `site:target.com -site:www.target.com`.",
  "**Public Data Aggregators & Search Engines** — many platforms constantly crawl the internet and archive DNS data.",
  "1. **VirusTotal** — provides passive DNS records and subdomains found in malware analysis.",
  "2. **Shodan / Censys** — internet-wide scanners that reveal subdomains mapped to IP addresses.",
  "3. **SecurityTrails** — offers historical DNS data and subdomain listings.",
  "**Automation Tools for Passive Hunting** — instead of checking every source manually, use tools that aggregate all of them at once.",
  "1. **Amass (Passive Mode):** `amass enum -passive -d target.com` — queries dozens of public data sources simultaneously.",
  "2. **Subfinder:** `subfinder -d target.com` — fast, lightweight, and highly effective at gathering passive data.",
  "## Active Subdomain Enumeration",
  "Active enumeration interacts directly with the target's DNS servers or infrastructure. It is louder but uncovers assets that passive sources missed.",
  "**DNS Brute-Forcing** — this technique tests thousands of potential subdomain names against the target's nameservers using a wordlist.",
  "1. **ShuffleDNS** — a fast wrapper around MassDNS that handles wildcard resolution effectively.",
  "2. **Gobuster:** `gobuster dns -d target.com -w wordlist.txt`",
  "> Tip: Recommended wordlists — `best-dns-wordlist.txt` (Assetnote) and `subdomains-top1million.txt` (SecLists).",
  "**Permutation and Alteration Generation** — after finding initial subdomains, create variations of those names (e.g., adding prefixes/suffixes like `dev-`, `-api`, `01`). **Altdns** generates permutations based on a dataset and resolves them — for example, if `api.target.com` exists, it also tests `dev-api.target.com`, `api-01.target.com`, and similar variants.",
  "**DNS Zone Transfer (AXFR)** — a misconfigured DNS server might allow anyone to copy its entire zone file, revealing all subdomains instantly: `dig axfr @ns1.target.com target.com`",
  "## The Methodology Workflow (Step-by-Step)",
  "To get the cleanest results, follow this structured pipeline:",
  "```\n[Target Domain]\n      |\n      +--> 1. Passive Collection (Subfinder, Amass, crt.sh) ---+\n      |                                                        |\n      +--> 2. Active Brute-Forcing (Gobuster, ShuffleDNS) -----+--> [Merged Subdomain List]\n                                                                |\n      +---------------------------------------------------------+\n      |\n      v\n3. DNS Resolution & Filtering (PureDNS / MassDNS)\n      |\n      v\n4. HTTP Probing & Alive Check (Httpx) --> [Valid, Live Targets for Pentesting]\n```",
  "1. **Run Passive Tools First:** extract everything from `subfinder` and `amass`.",
  "2. **Run Active Brute-Forcing:** generate potential subdomains using a strong wordlist.",
  "3. **Merge and Deduplicate:** combine the results into a single text file and remove duplicates — `cat passive.txt active.txt | sort -u > unique_subs.txt`",
  "4. **Resolve the Subdomains:** filter out dead domains using a fast resolver like PureDNS or MassDNS with trusted public resolvers (e.g., Cloudflare `1.1.1.1`, Google `8.8.8.8`).",
  "5. **Probe for Live Web Servers:** use `httpx` to check which subdomains actually run active web applications on ports 80 and 443 — `cat unique_subs.txt | httpx -title -tech-detect -status-code`",
  "## Key Takeaways for Students",
  "> Tip: Respect wildcards. Always identify if the target uses a wildcard DNS record (`*.target.com`) early on, otherwise brute-force tools will report thousands of false positives.",
  "> Tip: API keys matter. Tools like Subfinder and Amass work far better when configured with free API keys from services like SecurityTrails, BinaryEdge, and Shodan.",
  "> Tip: Stay updated. Infrastructure changes daily — running the enumeration pipeline weekly on the same target often yields new results.",
    ],
  },
  {
    id: 'blog-3',
    title: 'SIM Forensics A to Z in bangla: Investigating Mobile SIM Cards Part 1&2',
    excerpt: 'Basic to advanced techniques for extracting and analyzing data from mobile SIM cards, including IMSI, ICCID, and call logs.',
    date: 'july 2026',
    readTime: '10 min read',
    tags: ['SIM Forensics', 'Mobile Security'],
    slug: 'sim-forensics-a-to-z',
    content: [
      "## Part 1",
      "## Mobile Forensics কী?",
      "Mobile Forensics হলো কোনো মোবাইল ফোন বা SIM Card থেকে ডিজিটাল প্রমাণ (Digital Evidence) সংগ্রহ, বিশ্লেষণ এবং সংরক্ষণের প্রক্রিয়া। এটি Cyber Crime Investigation, Incident Response এবং Digital Investigation-এ ব্যবহৃত হয়।",
      "## এই কোর্সে কী শেখানো হবে?",
      "**১. SIM Card কী?** SIM (Subscriber Identity Module) হলো মোবাইলের একটি ছোট চিপ যেখানে ব্যবহারকারীর পরিচয় এবং নেটওয়ার্ক-সংক্রান্ত তথ্য সংরক্ষিত থাকে।",
      "**২. SIM Card-এর বিভিন্ন Format** — যেমন:",
      "- Standard SIM",
      "- Micro SIM",
      "- Nano SIM",
      "- eSIM (আধুনিক ফোনে)",
      "একজন Security Researcher-এর জন্য এগুলো জানা গুরুত্বপূর্ণ, কারণ বিভিন্ন ডিভাইসে বিভিন্ন ধরনের SIM ব্যবহৃত হয়।",
      "**৩. SIM Card Identifier** — SIM-এর মধ্যে কিছু গুরুত্বপূর্ণ ইউনিক আইডেন্টিফায়ার থাকে, যেমন:",
      "- **ICCID** – SIM Card-এর ইউনিক সিরিয়াল নম্বর।",
      "- **IMSI** – Subscriber-এর পরিচয় নম্বর, যা মোবাইল নেটওয়ার্ক ব্যবহার করে।",
      "- **Ki (Authentication Key)** – নেটওয়ার্কে নিরাপদ Authentication-এর জন্য ব্যবহৃত একটি গোপন Key।",
      "Investigation-এর সময় এগুলো বিশ্লেষণ করে ব্যবহারকারী ও নেটওয়ার্ক সম্পর্কিত তথ্য জানা যায়।",
      "**৪. SIM Clone** — SIM Clone হলো একটি SIM Card-এর তথ্য আরেকটি SIM-এ কপি করা।",
      "Security Research-এর ক্ষেত্রে:",
      "- বৈধ গবেষণা বা ফরেনসিক ল্যাবে পরীক্ষার জন্য এটি ব্যবহার করা হতে পারে।",
      "- অনুমতি ছাড়া অন্যের SIM Clone করা বেআইনি এবং অনৈতিক।",
      "**৫. SIM Imaging** — SIM Imaging বলতে SIM Card-এর একটি Forensic Copy তৈরি করা বোঝায়, যাতে আসল SIM পরিবর্তন না করেই তার ডেটা বিশ্লেষণ করা যায়।",
      "**৬. SIM Card থেকে কী ধরনের Data পাওয়া যায়?** — উদাহরণ:",
      "- Contacts",
      "- SMS",
      "- ICCID",
      "- IMSI",
      "- Network Information",
      "- Timestamp (কখন SMS পাঠানো বা গ্রহণ করা হয়েছে)",
      "এসব তথ্য তদন্তে গুরুত্বপূর্ণ ভূমিকা রাখে।",
      "## Learning Outcomes (এই কোর্স শেষে যা শিখবেন)",
      "এই কোর্স শেষে আপনি পারবেন:",
      "- SIM Card-এর বিভিন্ন Identifier বুঝতে।",
      "- মোবাইল থেকে SIM Identifier Decode করতে।",
      "- কখন SIM Clone ব্যবহার করা উচিত তা নির্ধারণ করতে।",
      "- Tool ব্যবহার করে SIM Card থেকে ডেটা সংগ্রহ করতে।",
      "- SIM Message-এর Timestamp Decode করতে।",
      "## একজন Security Researcher হিসেবে কেন এটি গুরুত্বপূর্ণ?",
      "এই বিষয়গুলো জানা থাকলে আপনি:",
      "- Mobile Forensics করতে পারবেন।",
      "- SIM Card থেকে Digital Evidence সংগ্রহ ও বিশ্লেষণ করতে পারবেন।",
      "- Cyber Crime Investigation-এ সহায়তা করতে পারবেন।",
      "- SIM-based Attack বা Fraud বিশ্লেষণ করতে পারবেন।",
      "- Mobile Device Security Research-এ আরও দক্ষ হতে পারবেন।",
      "## Part 2",
      "## অধ্যায় ১: Carrier Networks (বাংলায়)",
      "এই অধ্যায়ে মোবাইল নেটওয়ার্কের বিভিন্ন প্রযুক্তি সম্পর্কে আলোচনা করা হয়েছে। মূলত CDMA, GSM এবং LTE কী, তাদের পার্থক্য কী, এবং ফরেনসিক তদন্তে কেন এগুলো জানা দরকার — সেটিই ব্যাখ্যা করা হয়েছে।",
      "## Carrier Network কী?",
      "- Carrier Network বলতে মোবাইল অপারেটরের (যেমন Grameenphone, Robi, Banglalink, Airtel) সেই নেটওয়ার্ককে বোঝায় যার মাধ্যমে ফোনে Call, SMS এবং Internet ব্যবহার করা হয়।",
      "- প্রতিটি অপারেটর নির্দিষ্ট একটি বা একাধিক Network Standard ব্যবহার করে।",
      "## ১. CDMA (Code Division Multiple Access)",
      "CDMA একটি পুরোনো Mobile Communication Technology। বৈশিষ্ট্য:",
      "- একই সময়ে Call এবং Data পুরোপুরি ব্যবহার করা যেত না।",
      "- হয় Voice Call, নয় Data — এক সময়ে একটি।",
      "- Verizon, Sprint (আগে), US Cellular এই প্রযুক্তি ব্যবহার করত।",
      "## Security Researcher-এর জন্য",
      "CDMA ফোনে অনেক ক্ষেত্রে SIM Card নাও থাকতে পারে বা এর ব্যবহার GSM-এর তুলনায় ভিন্ন হতে পারে। তাই ফরেনসিক বিশ্লেষণের পদ্ধতিও ভিন্ন হতে পারে।",
      "## ২. GSM (Global System for Mobile Communications)",
      "এটি বিশ্বের সবচেয়ে জনপ্রিয় Mobile Network Standard। বাংলাদেশে:",
      "- Grameenphone",
      "- Robi",
      "- Banglalink",
      "- Airtel",
      "সবগুলো GSM প্রযুক্তির ওপর ভিত্তি করে শুরু হয়েছিল।",
      "**বৈশিষ্ট্য:**",
      "- SIM Card ব্যবহার করে।",
      "- একই সময়ে Call এবং Data ব্যবহার করা যায় (যদিও গতি কম)।",
      "## একজন Security Researcher-এর জন্য গুরুত্বপূর্ণ",
      "GSM নেটওয়ার্কে SIM Card থেকে পাওয়া যায়:",
      "- ICCID",
      "- IMSI",
      "- SMS",
      "- Contacts",
      "- Network Information",
      "এসব তথ্য Mobile Forensics-এ গুরুত্বপূর্ণ প্রমাণ হতে পারে।",
      "## ৩. LTE (Long-Term Evolution)",
      "LTE হলো 4G Technology। বর্তমানে অধিকাংশ স্মার্টফোন LTE ব্যবহার করে। বৈশিষ্ট্য:",
      "- একই সঙ্গে Call এবং High-Speed Internet।",
      "- GSM ও CDMA-এর তুলনায় অনেক দ্রুত।",
      "- AT&T, Verizon, T-Mobile সহ বিভিন্ন অপারেটর LTE ব্যবহার করে।",
      "## LTE কেন গুরুত্বপূর্ণ?",
      "LTE অনেক বেশি Bandwidth ব্যবহার করে। ফলে:",
      "- দ্রুত Download",
      "- দ্রুত Upload",
      "- HD Video Call",
      "- Online Gaming",
      "- দ্রুত Data Transfer সম্ভব।",
      "## 4G থেকে 5G",
      "বর্তমানে CDMA এবং GSM ধীরে ধীরে বন্ধ হয়ে যাচ্ছে এবং LTE দ্বারা প্রতিস্থাপিত হচ্ছে। 5G এসেছে LTE-এর উন্নত সংস্করণ হিসেবে, যেখানে আরও উচ্চ ফ্রিকোয়েন্সির রেডিও ব্যান্ড ব্যবহার করে আরও দ্রুত গতি প্রদান করা হয়।",
      "## একজন Mobile Forensics Investigator কেন এগুলো জানবে?",
      "যদি কোনো সন্দেহভাজনের ফোন বিশ্লেষণ করেন, তাহলে প্রথমেই জানতে হবে —",
      "- ফোনটি GSM নাকি CDMA?",
      "- LTE ব্যবহার করছে কি না?",
      "- SIM Card আছে কি?",
      "- কোন Carrier ব্যবহার হচ্ছে?",
      "কারণ এগুলোর ওপর নির্ভর করে Data Extraction-এর পদ্ধতি পরিবর্তিত হতে পারে।",
      "## Subset Networks",
      "## UMTS (Universal Mobile Telecommunications Service)",
      "UMTS হলো GSM-এর একটি উন্নত সংস্করণ। বৈশিষ্ট্য:",
      "- ২০০২ সালে চালু হয়।",
      "- GSM ও CDMA — দুটির ধারণা থেকে তৈরি।",
      "- বিশেষ হার্ডওয়্যার প্রয়োজন।",
      "- সেই সময়ে দ্রুত Data Speed দিত।",
      "## EDGE (Enhanced Data rates for GSM Evolution)",
      "EDGE-কে অনেক সময় 2.75G বলা হয়। এটি GSM Network-কে আরও দ্রুত Data Transfer করতে সাহায্য করত। ২০০৩ সালে এটি চালু হয়।",
      "## Security Researcher হিসেবে কী মনে রাখবেন?",
      "| Network | Generation | SIM ব্যবহার | Speed |",
      "| ------- | ---------- | --------------------- | ------------------ |",
      "| CDMA | 2G/3G | সীমিত বা ভিন্ন পদ্ধতি | ধীর |",
      "| GSM | 2G/3G | হ্যাঁ | মাঝারি |",
      "| EDGE | 2.75G | হ্যাঁ | GSM-এর চেয়ে দ্রুত |",
      "| UMTS | 3G | হ্যাঁ | দ্রুত |",
      "| LTE | 4G | হ্যাঁ | অনেক দ্রুত |",
      "| 5G | 5G | হ্যাঁ | সবচেয়ে দ্রুত |",
      "## ইন্টারভিউতে মনে রাখার বিষয়",
      "- **GSM** = SIM Card ভিত্তিক নেটওয়ার্ক।",
      "- **CDMA** = পুরোনো প্রযুক্তি, বর্তমানে প্রায় বিলুপ্ত।",
      "- **LTE** = 4G, দ্রুত Data ও Voice।",
      "- **UMTS** = GSM-এর 3G উন্নত সংস্করণ।",
      "- **EDGE** = GSM-এর দ্রুততর 2.75G সংস্করণ।",
      "> ধন্যবাদ। শীঘ্রই পরবর্তী অংশ (Part 3) নিয়ে আসছি।",
    ],
  },
];

export const terminalCommands: Record<string, string[]> = {
  whoami: ['Cyber Security Engineer'],
  help: [
    'Available commands:',
    '  whoami     - display current user role',
    '  skills     - list core skill areas',
    '  projects   - jump to projects section',
    '  contact    - jump to contact section',
    '  clear      - clear the terminal',
  ],
  skills: [
    'Programming   : Python, Bash, JavaScript, PHP, SQL, Rust',
    'Security      : Web Pentesting, API Security, Network Security, OSINT',
    'Tools         : Burp Suite, Nmap, Metasploit, Wireshark, SQLMap, more...',
  ],
};
