import {
  Achievement,
  BlogPost,
  Certification,
  EducationItem,
  ExperienceItem,
  Project,
  ServiceItem,
  SkillCategory,
  TimelineItem,
} from '@/types';

export const siteConfig = {
  name: 'Md Minhaj',
  role: 'Cyber Security Researcher & Penetration Tester',
  roles: ['Cyber Security Researcher', 'Ethical Hacker', 'Penetration Tester', 'Security Researcher', 'Bug Bounty Hunter'],
  typingWords: [
    'Penetration Testing',
    'Web Security',
    'Red Team',
    'OSINT',
    'Digital Forensics',
    'Network Security',
    'Malware Analysis',
  ],
  email: 'pentester.minhaj@gmail.com',
  github: 'https://github.com/Md-Minhaj-darkness',
  linkedin: 'https://www.linkedin.com/in/md-minhaj-darkness/',
  twitter: 'https://x.com/MDMINHA17101032',
  discord: 'https://discord.com/users/1316397974338797580',
  resumeUrl: '/resume/resume.pdf',
  location: 'Remote / Worldwide',
  about: `I'm a Cybersecurity Researcher, Penetration Tester, and Digital Forensics Practitioner specializing in offensive security, vulnerability research, and incident investigation. My expertise includes web application security, malware analysis, incident response, Linux, networking, and secure software development.

I enjoy discovering vulnerabilities, analyzing digital evidence, building security tools, and sharing practical cybersecurity knowledge through technical content and online training. I believe continuous learning is the foundation of staying ahead in cybersecurity.
.`,
};

export const services: ServiceItem[] = [
  { id: 'MOD-01', title: 'Web Application Penetration Testing', status: 'ACTIVE' },
  { id: 'MOD-02', title: 'API Security Testing & Assessment', status: 'ACTIVE' },
  { id: 'MOD-03', title: 'AI & LLM Security Testing', status: 'ACTIVE' },
  { id: 'MOD-04', title: 'Red Teaming & Adversary Simulation', status: 'ACTIVE' },
  //{ id: 'MOD-05', title: 'Governance, Risk & Compliance Advisory', status: 'ACTIVE' },
  { id: 'MOD-06', title: 'Security Awareness & Training Programs', status: 'ACTIVE' },
  //{ id: 'MOD-07', title: 'Security Monitoring & Data Protection', status: 'ACTIVE' },
  { id: 'MOD-08', title: 'Incident Response & Threat Management', status: 'ACTIVE' },
];

export const aboutHighlights = [
  { title: 'Ethical Hacking', desc: 'Authorized offensive testing to uncover exploitable weaknesses before attackers do.' },
  { title: 'Web App Security', desc: 'Deep focus on OWASP Top 10, business logic flaws, and modern web attack surfaces.' },
  { title: 'Vulnerability Assessment', desc: 'Structured methodology for identifying, validating, and prioritizing risk.' },
  { title: 'Penetration Testing', desc: 'End-to-end engagements: recon, exploitation, privilege escalation, reporting.' },
  { title: 'Secure Coding', desc: 'Building and reviewing code with a security-first mindset from the ground up.' },
  { title: 'Linux & Networking', desc: 'Comfortable at the command line, from packet captures to kernel-level detail.' },
  { title: 'Continuous Learning', desc: 'Always in a lab, a CTF, or a writeup — the field moves fast and so do I.' },
  { title: 'Digital Forensics', desc: 'Digital evidence acquisition, analysis, recovery, and cybercrime investigation using industry-standard forensic methodologies.' },
];

export const skillCategories: SkillCategory[] = [
  {
    title: 'Programming',
    icon: 'Code2',
    skills: [
      { name: 'Python', level: 90 },
      { name: 'Bash', level: 88 },
      { name: 'JavaScript', level: 78 },
      { name: 'PHP', level: 70 },
      { name: 'SQL', level: 80 },
    ],
  },
  {
    title: 'Operating Systems',
    icon: 'Terminal',
    skills: [
      { name: 'Kali Linux', level: 95 },
      { name: 'Ubuntu', level: 88 },
      { name: 'Windows', level: 82 },
    ],
  },
  {
    title: 'Security Domains',
    icon: 'ShieldHalf',
    skills: [
      { name: 'Web Pentesting', level: 92 },
      { name: 'API Security', level: 85 },
      { name: 'Network Security', level: 84 },
      { name: 'Active Directory', level: 75 },
      { name: 'OSINT', level: 86 },
      { name: 'Digital Forensics', level: 82 },
      { name: 'Malware Analysis', level: 72 },
      { name: 'Threat Hunting', level: 82 },
    ],
  },
  {
    title: 'Tools',
    icon: 'Wrench',
    skills: [
      { name: 'Burp Suite', level: 92 },
      { name: 'Nmap', level: 90 },
      { name: 'Metasploit', level: 82 },
      { name: 'Wireshark', level: 80 },
      { name: 'Nessus', level: 75 },
      { name: 'OWASP ZAP', level: 85 },
      { name: 'Hydra', level: 78 },
      { name: 'Gobuster', level: 88 },
      { name: 'ffuf', level: 85 },
      { name: 'SQLMap', level: 84 },
      { name: 'Nikto', level: 76 },
      { name: 'John the Ripper', level: 74 },
      { name: 'Hashcat', level: 74 },
      { name: 'BloodHound', level: 70 },
    ],
  },
];

export const projects: Project[] = [
  {
    id: 'proj-1',
    title: 'Subdomain Takeover Scanner',
    description:
      'A CLI tool that automates passive enumeration and CNAME fingerprinting to flag potentially vulnerable subdomains across large scopes.',
    image: '/images/projects/placeholder-1.svg',
    technologies: ['Python', 'DNS', 'Requests', 'Asyncio'],
    category: 'Tooling',
    section: 'Featured',
    github: 'https://github.com/yourusername/subtakeover-scanner',
    demo: '',
    date: '2026',
  },
  {
    id: 'proj-2',
    title: 'Web App Pentest Report — E-Commerce Client',
    description:
      'Full black-box assessment covering authentication flaws, IDOR, and stored XSS with a remediation-focused report.',
    image: '/images/projects/placeholder-2.svg',
    technologies: ['Burp Suite', 'OWASP Top 10', 'Manual Testing'],
    category: 'Web Pentest',
    section: 'Featured',
    github: '',
    demo: '',
    date: '2026',
  },
  {
    id: 'proj-3',
    title: 'Internal Network Segmentation Audit',
    description:
      'Simulated lateral movement inside a segmented lab environment to validate firewall rules and VLAN isolation.',
    image: '/images/projects/placeholder-3.svg',
    technologies: ['Nmap', 'Wireshark', 'pfSense'],
    category: 'Network Security',
    section: 'Labs',
    github: 'https://github.com/yourusername/network-seg-lab',
    date: '2025',
  },
  {
    id: 'proj-4',
    title: 'HTB — "Forest" Writeup',
    description:
      'Active Directory box exploited via anonymous LDAP bind, then privilege escalation through certificate services.',
    image: '/images/projects/placeholder-4.svg',
    technologies: ['Active Directory', 'BloodHound', 'Impacket'],
    category: 'Network Security',
    section: 'CTF Writeups',
    github: 'https://github.com/yourusername/htb-writeups',
    date: '2025',
  },
  {
    id: 'proj-5',
    title: 'OSINT Framework for Employee Footprinting',
    description:
      'Research project mapping open-source techniques for corporate attack-surface discovery via employee digital footprints.',
    image: '/images/projects/placeholder-5.svg',
    technologies: ['OSINT', 'Python', 'Recon-ng'],
    category: 'OSINT',
    section: 'Security Research',
    github: 'https://github.com/yourusername/osint-footprint',
    date: '2025',
  },
  {
    id: 'proj-6',
    title: 'ffuf Wordlist Contribution',
    description:
      'Contributed curated fuzzing wordlists and fixed edge-case bugs in a popular open-source fuzzing project.',
    image: '/images/projects/placeholder-6.svg',
    technologies: ['ffuf', 'Go', 'Wordlists'],
    category: 'Tooling',
    section: 'Open Source',
    github: 'https://github.com/yourusername/ffuf-contrib',
    date: '2025',
  },
];

export const projectSections = ['Featured', 'Labs', 'CTF Writeups', 'Security Research', 'Open Source'] as const;

export const achievements: Achievement[] = [
  { title: 'Hall of Fame & bug bounty', issuer: 'HackerOne', date: '2025', type: 'Bug Bounty' },
  { title: 'ACP Certified', issuer: 'APISEC', date: '2025', type: 'Certification' },
  { title: 'TryHackMe Lab Solve', issuer: 'TryHackMe', date: '2025', type: 'CTF' },
  { title: 'Hall of Fame', issuer: 'Bugcrowd', date: '2025', type: 'Bug Bounty' },
  { title: 'Hall of Fame', issuer: 'Self Host Program', date: '2025', type: 'Bug Bounty' },
  { title: 'Lab & CTF Solve', issuer: 'Root-me', date: '2024', type: 'CTF' },
];

export const learningJourney: TimelineItem[] = [
  { year: '2021', title: 'First Steps', description: 'Discovered ethical hacking through CTFs and started learning Linux fundamentals.' },
  { year: '2022', title: 'Foundations', description: 'Built networking and scripting fundamentals; completed first vulnerable-machine walkthroughs.' },
  { year: '2023', title: 'Specialization', description: 'Focused on web application security and started participating in bug bounty programs.' },
  { year: '2024', title: 'Certification & Community', description: 'Earned eJPT, began publishing writeups, and joined the local security community.' },
  { year: '2025', title: 'Professional Growth', description: 'Delivered first client pentest engagements and expanded into Active Directory attacks.' },
  { year: '2026', title: 'Today', description: 'Working toward OSCP while contributing to open-source security tooling.' },
];

export const experience: ExperienceItem[] = [
  {
    role: 'Bug Bounty Hunter',
    company: 'HackerOne Platform',
    duration: '2023 — Present',
    location: 'Remote',
    points: [
      'Conducted black-box and gray-box web application assessments on various programs via the HackerOne platform.',
      'Authored professional-grade findings reports with CVSS scoring and remediation guidance.',
      'Collaborated with blue team counterparts on detection validation post-engagement.',
    ],
  },
  {
    role: 'jr. Penetration Tester',
    company: 'bytecapsuleit',
    duration: '2024 — 2025',
    location: 'Hybrid',
    points: [
      'Researched emerging CVEs and reproduced proof-of-concept exploits in isolated lab environments.',
      'Built internal tooling to automate recon phases of engagements, cutting setup time significantly.',
    ],
  },
];

export const education: EducationItem[] = [
  {
    degree: 'Cyber Security',
    institution: 'Coursera / Udemy / Google / other online platforms',
    duration: '2022 — 2026',
    location: 'Online Learning',
    description: 'Focused coursework in network security, cryptography, and systems programming.',
  },
];

export const certifications: Certification[] = [
  { name: 'Ethical Hacking For Professionals', shortName: 'EHP', issuer: 'bytecapsuleit', status: 'Completed', year: '2025', color: '#00ff9c' },
  { name: 'APIsec Certified Practitioner', shortName: 'ACP', issuer: 'APISEC', status: 'Completed', year: '2025', color: '#00ff9c' },
  { name: 'Basic to Advanced Digital Forensics & Cyber Crime Investigation', shortName: 'DFIR', issuer: 'bytecapsuleit', status: 'Completed', year: '2025', color: '#00ff9c' },
  { name: 'Mastering Android Bug Bounties with Personal PoC', shortName: 'MABB', issuer: 'Udemy', status: 'Completed', year: '2025', color: '#00ff9c' },
  { name: 'Offensive Security Certified Professional', shortName: 'OSCP', issuer: 'Offensive Security', status: 'Future Goal', color: '#ffb800' },
  { name: 'Offensive API Exploitation', shortName: 'API Exploitation', issuer: 'Udemy', status: 'Completed', year: '2024', color: '#00ff9c' },
  { name: 'Practical Bug Bounty', shortName: 'PBB', issuer: 'TCM Security', status: 'Completed', year: '2023', color: '#00ff9c' },
  { name: 'Practical API Hacking', shortName: 'PAH', issuer: 'TCM Security', status: 'Completed', year: '2023', color: '#00ff9c' },
];

export const stats = [
  { label: 'Projects', value: 60 },
  { label: 'Labs Completed', value: 120 },
  { label: 'CTFs Played', value: 10 },
  { label: 'GitHub Contributions', value: 100 },
  { label: 'Certifications', value: 10 },
];

export const blogPosts: BlogPost[] = [
  {
    id: 'blog-1',
    title: 'Understanding IDOR: Hunting Tips and Techniques',
    excerpt: 'A practical look at how Insecure Direct Object References slip past code review and how to hunt for them systematically.',
    date: 'Jun 2026',
    readTime: '6 min read',
    tags: ['Web Security', 'OWASP'],
    slug: 'understanding-idor',
    content: [
    "Insecure Direct Object References (IDOR) remain one of the most common — and most overlooked — vulnerabilities in modern web applications. They happen when an application exposes a reference to an internal object, like a database ID, without properly verifying that the requesting user is actually authorized to access it.",
  "To understand IDOR, think of a hotel. Authentication is the front desk checking your ID and giving you a room key card. Authorization is making sure your key card only opens your assigned room, not the penthouse suite next door. An IDOR happens when the hotel door lets you in just because you changed the room number written on your card.",
  "## Why IDOR Slips Past Code Review",
  "Most IDOR bugs are not the result of bad code in isolation. They emerge from the gap between authentication (who you are) and authorization (what you are allowed to touch).",
  "When reviewing code, developers often check off a mental list: \"Is the user logged in? Yes. Is the session valid? Yes.\" Because the code looks secure on the surface, the bug slips through. The developer correctly verifies that a user is logged in, but completely forgets to check if the specific record being requested actually belongs to that user. In modern applications built on microservices and complex APIs, tracking data ownership across multiple database tables makes this even harder to spot during a manual code review.",
  "## A Systematic Hunting Approach",
  "To find IDOR vulnerabilities systematically, you must adopt a methodical testing workflow rather than randomly guessing numbers.",
  "1. **Map the Attack Surface:** Start by mapping every single endpoint that accepts an identifier. Look closely at API routes (/api/v1/orders/1024), query parameters (?invoice_id=9982), and request bodies. Identify user IDs, order numbers, invoice references, account settings, and file paths.",
  "2. **Establish Multi-Tenant Personas:** Set up at least two distinct user accounts with the exact same privilege levels (e.g., User A and User B, both standard customers).",
  "3. **The Swap Test:** Capture a request made by User A (for example, viewing User A's private profile). Change the identifier in that request to match User B's identifier.",
  "4. **Analyze the Response:** If User A can view or modify User B's data, you have successfully discovered an IDOR.",
  "> Tip: Pay special attention to feature additions. Endpoints added later in a project's life cycle are highly prone to IDORs because they are often rushed or bolted on without thoroughly integrating into the application's core authorization model.",
  "> Tip: Advanced IDOR hunting goes beyond simple parameter manipulation to exploit hidden API structures, state management flaws, and method tampering. Key hidden vectors include HPP, changing content types (JSON/XML), abusing leaked UUIDs, version downgrading (/v3/ to /v2/), and second-order IDORs where inputs are stored and executed later.",
  "## Practical Hunting Tips & Automation",
  "Hunting IDORs manually across hundreds of endpoints is exhausting. Modern bug hunters and penetration testers use smart automation to scale their efforts.",
  "**Automate with Burp Suite:** Capture a full authenticated session of User A using Burp Suite. Then, utilize extensions like Authorize or Match and Replace to automatically swap User A's session token/cookie with User B's session token on every outgoing request. Any request that still returns a 200 OK status code with actual data payload requires an immediate, closer look.",
  "**Look Beyond Sequential Integers:** While sequential IDs (1, 2, 3...) are the easiest to exploit, do not ignore UUIDs (Universally Unique Identifiers) or encoded strings (like Base64 hashes). If a UUID is leaked in a public forum, a comment section, or an unauthenticated API endpoint, it can still be used to trigger an IDOR if the backend lacks authorization checks.",
  "**Test All HTTP Methods:** An endpoint might be secure against unauthorized reading (GET), but completely vulnerable to unauthorized modification (PUT, POST, DELETE). Always check if you can delete or edit another user's resources.",
  "## Conclusion",
  "IDOR is incredibly simple to explain but remarkably easy to miss at scale. It requires no complex exploit payloads or memory corruption knowledge — just a fundamental understanding of how logic flows through an application. Treating authorization checks as a first-class concern, validated on every single object-returning endpoint, is the only reliable defense.",
    ],
  },
  {
    id: 'blog-2',
    title: 'My Subdomain Enumeration Methodology',
    excerpt: 'The passive and active recon workflow I use before touching a single endpoint during bug bounty hunting.',
    date: 'May 2026',
    readTime: '8 min read',
    tags: ['Recon', 'Bug Bounty'],
    slug: 'subdomain-enum-methodology',
     content: [
      "Subdomain enumeration is the process of finding valid subdomains for a target domain. It expands the attack surface and reveals hidden assets, staging environments, or forgotten portals. A robust methodology combines Passive and Active techniques.",
  "## Passive Subdomain Enumeration",
  "Passive enumeration gathers data from third-party sources without directly interacting with the target's infrastructure. This minimizes the risk of detection.",
  "**Certificate Transparency (CT) Logs** — Certificate Authorities (CAs) publicly log every SSL/TLS certificate issued. These logs are a goldmine for subdomains.",
  "1. `crt.sh` — a web-based interface to search CT logs.",
  "2. **Certspotter** — monitors CT logs in real-time.",
  "**Search Engine Scraping (Google Dorking)** — search engines index subdomains automatically. You can filter results to exclude the main domain using the operator `site:target.com -site:www.target.com`.",
  "**Public Data Aggregators & Search Engines** — many platforms constantly crawl the internet and archive DNS data.",
  "1. **VirusTotal** — provides passive DNS records and subdomains found in malware analysis.",
  "2. **Shodan / Censys** — internet-wide scanners that reveal subdomains mapped to IP addresses.",
  "3. **SecurityTrails** — offers historical DNS data and subdomain listings.",
  "**Automation Tools for Passive Hunting** — instead of checking every source manually, use tools that aggregate all of them at once.",
  "1. **Amass (Passive Mode):** `amass enum -passive -d target.com` — queries dozens of public data sources simultaneously.",
  "2. **Subfinder:** `subfinder -d target.com` — fast, lightweight, and highly effective at gathering passive data.",
  "## Active Subdomain Enumeration",
  "Active enumeration interacts directly with the target's DNS servers or infrastructure. It is louder but uncovers assets that passive sources missed.",
  "**DNS Brute-Forcing** — this technique tests thousands of potential subdomain names against the target's nameservers using a wordlist.",
  "1. **ShuffleDNS** — a fast wrapper around MassDNS that handles wildcard resolution effectively.",
  "2. **Gobuster:** `gobuster dns -d target.com -w wordlist.txt`",
  "> Tip: Recommended wordlists — `best-dns-wordlist.txt` (Assetnote) and `subdomains-top1million.txt` (SecLists).",
  "**Permutation and Alteration Generation** — after finding initial subdomains, create variations of those names (e.g., adding prefixes/suffixes like `dev-`, `-api`, `01`). **Altdns** generates permutations based on a dataset and resolves them — for example, if `api.target.com` exists, it also tests `dev-api.target.com`, `api-01.target.com`, and similar variants.",
  "**DNS Zone Transfer (AXFR)** — a misconfigured DNS server might allow anyone to copy its entire zone file, revealing all subdomains instantly: `dig axfr @ns1.target.com target.com`",
  "## The Methodology Workflow (Step-by-Step)",
  "To get the cleanest results, follow this structured pipeline:",
  "```\n[Target Domain]\n      |\n      +--> 1. Passive Collection (Subfinder, Amass, crt.sh) ---+\n      |                                                        |\n      +--> 2. Active Brute-Forcing (Gobuster, ShuffleDNS) -----+--> [Merged Subdomain List]\n                                                                |\n      +---------------------------------------------------------+\n      |\n      v\n3. DNS Resolution & Filtering (PureDNS / MassDNS)\n      |\n      v\n4. HTTP Probing & Alive Check (Httpx) --> [Valid, Live Targets for Pentesting]\n```",
  "1. **Run Passive Tools First:** extract everything from `subfinder` and `amass`.",
  "2. **Run Active Brute-Forcing:** generate potential subdomains using a strong wordlist.",
  "3. **Merge and Deduplicate:** combine the results into a single text file and remove duplicates — `cat passive.txt active.txt | sort -u > unique_subs.txt`",
  "4. **Resolve the Subdomains:** filter out dead domains using a fast resolver like PureDNS or MassDNS with trusted public resolvers (e.g., Cloudflare `1.1.1.1`, Google `8.8.8.8`).",
  "5. **Probe for Live Web Servers:** use `httpx` to check which subdomains actually run active web applications on ports 80 and 443 — `cat unique_subs.txt | httpx -title -tech-detect -status-code`",
  "## Key Takeaways for Students",
  "> Tip: Respect wildcards. Always identify if the target uses a wildcard DNS record (`*.target.com`) early on, otherwise brute-force tools will report thousands of false positives.",
  "> Tip: API keys matter. Tools like Subfinder and Amass work far better when configured with free API keys from services like SecurityTrails, BinaryEdge, and Shodan.",
  "> Tip: Stay updated. Infrastructure changes daily — running the enumeration pipeline weekly on the same target often yields new results.",
    ],
  },
  {
    id: 'blog-3',
    title: 'SIM Forensics A to Z in bangla: Investigating Mobile SIM Cards Part 1&2',
    excerpt: 'Basic to advanced techniques for extracting and analyzing data from mobile SIM cards, including IMSI, ICCID, and call logs.',
    date: 'july 2026',
    readTime: '10 min read',
    tags: ['SIM Forensics', 'Mobile Security'],
    slug: 'sim-forensics-a-to-z',
    content: [
      "## Part 1",
      "## Mobile Forensics কী?",
      "Mobile Forensics হলো কোনো মোবাইল ফোন বা SIM Card থেকে ডিজিটাল প্রমাণ (Digital Evidence) সংগ্রহ, বিশ্লেষণ এবং সংরক্ষণের প্রক্রিয়া। এটি Cyber Crime Investigation, Incident Response এবং Digital Investigation-এ ব্যবহৃত হয়।",
      "## এই কোর্সে কী শেখানো হবে?",
      "**১. SIM Card কী?** SIM (Subscriber Identity Module) হলো মোবাইলের একটি ছোট চিপ যেখানে ব্যবহারকারীর পরিচয় এবং নেটওয়ার্ক-সংক্রান্ত তথ্য সংরক্ষিত থাকে।",
      "**২. SIM Card-এর বিভিন্ন Format** — যেমন:",
      "- Standard SIM",
      "- Micro SIM",
      "- Nano SIM",
      "- eSIM (আধুনিক ফোনে)",
      "একজন Security Researcher-এর জন্য এগুলো জানা গুরুত্বপূর্ণ, কারণ বিভিন্ন ডিভাইসে বিভিন্ন ধরনের SIM ব্যবহৃত হয়।",
      "**৩. SIM Card Identifier** — SIM-এর মধ্যে কিছু গুরুত্বপূর্ণ ইউনিক আইডেন্টিফায়ার থাকে, যেমন:",
      "- **ICCID** – SIM Card-এর ইউনিক সিরিয়াল নম্বর।",
      "- **IMSI** – Subscriber-এর পরিচয় নম্বর, যা মোবাইল নেটওয়ার্ক ব্যবহার করে।",
      "- **Ki (Authentication Key)** – নেটওয়ার্কে নিরাপদ Authentication-এর জন্য ব্যবহৃত একটি গোপন Key।",
      "Investigation-এর সময় এগুলো বিশ্লেষণ করে ব্যবহারকারী ও নেটওয়ার্ক সম্পর্কিত তথ্য জানা যায়।",
      "**৪. SIM Clone** — SIM Clone হলো একটি SIM Card-এর তথ্য আরেকটি SIM-এ কপি করা।",
      "Security Research-এর ক্ষেত্রে:",
      "- বৈধ গবেষণা বা ফরেনসিক ল্যাবে পরীক্ষার জন্য এটি ব্যবহার করা হতে পারে।",
      "- অনুমতি ছাড়া অন্যের SIM Clone করা বেআইনি এবং অনৈতিক।",
      "**৫. SIM Imaging** — SIM Imaging বলতে SIM Card-এর একটি Forensic Copy তৈরি করা বোঝায়, যাতে আসল SIM পরিবর্তন না করেই তার ডেটা বিশ্লেষণ করা যায়।",
      "**৬. SIM Card থেকে কী ধরনের Data পাওয়া যায়?** — উদাহরণ:",
      "- Contacts",
      "- SMS",
      "- ICCID",
      "- IMSI",
      "- Network Information",
      "- Timestamp (কখন SMS পাঠানো বা গ্রহণ করা হয়েছে)",
      "এসব তথ্য তদন্তে গুরুত্বপূর্ণ ভূমিকা রাখে।",
      "## Learning Outcomes (এই কোর্স শেষে যা শিখবেন)",
      "এই কোর্স শেষে আপনি পারবেন:",
      "- SIM Card-এর বিভিন্ন Identifier বুঝতে।",
      "- মোবাইল থেকে SIM Identifier Decode করতে।",
      "- কখন SIM Clone ব্যবহার করা উচিত তা নির্ধারণ করতে।",
      "- Tool ব্যবহার করে SIM Card থেকে ডেটা সংগ্রহ করতে।",
      "- SIM Message-এর Timestamp Decode করতে।",
      "## একজন Security Researcher হিসেবে কেন এটি গুরুত্বপূর্ণ?",
      "এই বিষয়গুলো জানা থাকলে আপনি:",
      "- Mobile Forensics করতে পারবেন।",
      "- SIM Card থেকে Digital Evidence সংগ্রহ ও বিশ্লেষণ করতে পারবেন।",
      "- Cyber Crime Investigation-এ সহায়তা করতে পারবেন।",
      "- SIM-based Attack বা Fraud বিশ্লেষণ করতে পারবেন।",
      "- Mobile Device Security Research-এ আরও দক্ষ হতে পারবেন।",
      "## Part 2",
      "## অধ্যায় ১: Carrier Networks (বাংলায়)",
      "এই অধ্যায়ে মোবাইল নেটওয়ার্কের বিভিন্ন প্রযুক্তি সম্পর্কে আলোচনা করা হয়েছে। মূলত CDMA, GSM এবং LTE কী, তাদের পার্থক্য কী, এবং ফরেনসিক তদন্তে কেন এগুলো জানা দরকার — সেটিই ব্যাখ্যা করা হয়েছে।",
      "## Carrier Network কী?",
      "- Carrier Network বলতে মোবাইল অপারেটরের (যেমন Grameenphone, Robi, Banglalink, Airtel) সেই নেটওয়ার্ককে বোঝায় যার মাধ্যমে ফোনে Call, SMS এবং Internet ব্যবহার করা হয়।",
      "- প্রতিটি অপারেটর নির্দিষ্ট একটি বা একাধিক Network Standard ব্যবহার করে।",
      "## ১. CDMA (Code Division Multiple Access)",
      "CDMA একটি পুরোনো Mobile Communication Technology। বৈশিষ্ট্য:",
      "- একই সময়ে Call এবং Data পুরোপুরি ব্যবহার করা যেত না।",
      "- হয় Voice Call, নয় Data — এক সময়ে একটি।",
      "- Verizon, Sprint (আগে), US Cellular এই প্রযুক্তি ব্যবহার করত।",
      "## Security Researcher-এর জন্য",
      "CDMA ফোনে অনেক ক্ষেত্রে SIM Card নাও থাকতে পারে বা এর ব্যবহার GSM-এর তুলনায় ভিন্ন হতে পারে। তাই ফরেনসিক বিশ্লেষণের পদ্ধতিও ভিন্ন হতে পারে।",
      "## ২. GSM (Global System for Mobile Communications)",
      "এটি বিশ্বের সবচেয়ে জনপ্রিয় Mobile Network Standard। বাংলাদেশে:",
      "- Grameenphone",
      "- Robi",
      "- Banglalink",
      "- Airtel",
      "সবগুলো GSM প্রযুক্তির ওপর ভিত্তি করে শুরু হয়েছিল।",
      "**বৈশিষ্ট্য:**",
      "- SIM Card ব্যবহার করে।",
      "- একই সময়ে Call এবং Data ব্যবহার করা যায় (যদিও গতি কম)।",
      "## একজন Security Researcher-এর জন্য গুরুত্বপূর্ণ",
      "GSM নেটওয়ার্কে SIM Card থেকে পাওয়া যায়:",
      "- ICCID",
      "- IMSI",
      "- SMS",
      "- Contacts",
      "- Network Information",
      "এসব তথ্য Mobile Forensics-এ গুরুত্বপূর্ণ প্রমাণ হতে পারে।",
      "## ৩. LTE (Long-Term Evolution)",
      "LTE হলো 4G Technology। বর্তমানে অধিকাংশ স্মার্টফোন LTE ব্যবহার করে। বৈশিষ্ট্য:",
      "- একই সঙ্গে Call এবং High-Speed Internet।",
      "- GSM ও CDMA-এর তুলনায় অনেক দ্রুত।",
      "- AT&T, Verizon, T-Mobile সহ বিভিন্ন অপারেটর LTE ব্যবহার করে।",
      "## LTE কেন গুরুত্বপূর্ণ?",
      "LTE অনেক বেশি Bandwidth ব্যবহার করে। ফলে:",
      "- দ্রুত Download",
      "- দ্রুত Upload",
      "- HD Video Call",
      "- Online Gaming",
      "- দ্রুত Data Transfer সম্ভব।",
      "## 4G থেকে 5G",
      "বর্তমানে CDMA এবং GSM ধীরে ধীরে বন্ধ হয়ে যাচ্ছে এবং LTE দ্বারা প্রতিস্থাপিত হচ্ছে। 5G এসেছে LTE-এর উন্নত সংস্করণ হিসেবে, যেখানে আরও উচ্চ ফ্রিকোয়েন্সির রেডিও ব্যান্ড ব্যবহার করে আরও দ্রুত গতি প্রদান করা হয়।",
      "## একজন Mobile Forensics Investigator কেন এগুলো জানবে?",
      "যদি কোনো সন্দেহভাজনের ফোন বিশ্লেষণ করেন, তাহলে প্রথমেই জানতে হবে —",
      "- ফোনটি GSM নাকি CDMA?",
      "- LTE ব্যবহার করছে কি না?",
      "- SIM Card আছে কি?",
      "- কোন Carrier ব্যবহার হচ্ছে?",
      "কারণ এগুলোর ওপর নির্ভর করে Data Extraction-এর পদ্ধতি পরিবর্তিত হতে পারে।",
      "## Subset Networks",
      "## UMTS (Universal Mobile Telecommunications Service)",
      "UMTS হলো GSM-এর একটি উন্নত সংস্করণ। বৈশিষ্ট্য:",
      "- ২০০২ সালে চালু হয়।",
      "- GSM ও CDMA — দুটির ধারণা থেকে তৈরি।",
      "- বিশেষ হার্ডওয়্যার প্রয়োজন।",
      "- সেই সময়ে দ্রুত Data Speed দিত।",
      "## EDGE (Enhanced Data rates for GSM Evolution)",
      "EDGE-কে অনেক সময় 2.75G বলা হয়। এটি GSM Network-কে আরও দ্রুত Data Transfer করতে সাহায্য করত। ২০০৩ সালে এটি চালু হয়।",
      "## Security Researcher হিসেবে কী মনে রাখবেন?",
      "| Network | Generation | SIM ব্যবহার | Speed |",
      "| ------- | ---------- | --------------------- | ------------------ |",
      "| CDMA | 2G/3G | সীমিত বা ভিন্ন পদ্ধতি | ধীর |",
      "| GSM | 2G/3G | হ্যাঁ | মাঝারি |",
      "| EDGE | 2.75G | হ্যাঁ | GSM-এর চেয়ে দ্রুত |",
      "| UMTS | 3G | হ্যাঁ | দ্রুত |",
      "| LTE | 4G | হ্যাঁ | অনেক দ্রুত |",
      "| 5G | 5G | হ্যাঁ | সবচেয়ে দ্রুত |",
      "## ইন্টারভিউতে মনে রাখার বিষয়",
      "- **GSM** = SIM Card ভিত্তিক নেটওয়ার্ক।",
      "- **CDMA** = পুরোনো প্রযুক্তি, বর্তমানে প্রায় বিলুপ্ত।",
      "- **LTE** = 4G, দ্রুত Data ও Voice।",
      "- **UMTS** = GSM-এর 3G উন্নত সংস্করণ।",
      "- **EDGE** = GSM-এর দ্রুততর 2.75G সংস্করণ।",
      "> ধন্যবাদ। শীঘ্রই পরবর্তী অংশ (Part 3&4) নিয়ে আসছি।",
    ],
  },
  {
    id: 'blog-4',
    title: 'SIM Forensics A to Z in bangla: Investigating Mobile SIM Cards Part 3&4',
    excerpt: 'Basic to advanced techniques for extracting and analyzing data from mobile SIM cards, including IMSI, ICCID, and call logs.',
    date: 'july 2026',
    readTime: '15 min read',
    tags: ['SIM Forensics', 'Mobile Security'],
    slug: 'sim-forensics-a-to-z-part-3-4',
    content: [
       "## Part 3",
  "## What are SIM Cards?",
  "এই অধ্যায়ে ব্যাখ্যা করা হয়েছে SIM Card আসলে কী, কীভাবে কাজ করে, Smart Card কী, UICC কী, এবং SIM Card-এর ভিতরে কী কী থাকে।",
  "## SIM Card কী?",
  "SIM (Subscriber Identity Module) হলো একটি ছোট ইলেকট্রনিক চিপ, যা মোবাইল ফোনকে মোবাইল অপারেটরের (Carrier) নেটওয়ার্কে সংযুক্ত হতে সাহায্য করে।",
  "সহজ ভাষায়,",
  "- **Phone** = Hardware",
  "- **SIM** = আপনার পরিচয় (Identity)",
  "SIM Card ছাড়া সাধারণ GSM ফোনে Call, SMS বা Mobile Network ব্যবহার করা যায় না।",
  "## SIM Card-এ কী থাকে?",
  "SIM Card-এর ভিতরে গুরুত্বপূর্ণ তথ্য সংরক্ষিত থাকে, যেমন:",
  "- IMSI (Subscriber Identity)",
  "- Authentication Key (Ki)",
  "- Phonebook (কিছু SIM-এ)",
  "- SMS",
  "- Carrier Information",
  "- Security Keys",
  "এই তথ্য ব্যবহার করে মোবাইল নেটওয়ার্ক নিশ্চিত করে যে আপনি বৈধ গ্রাহক।",
  "## Smart Card কী?",
  "SIM Card আসলে একটি Smart Card।",
  "Smart Card হলো এমন একটি ছোট কম্পিউটার চিপ, যার ভিতরে থাকে—",
  "- Microprocessor (CPU)",
  "- Operating System",
  "- File System",
  "- Memory",
  "অর্থাৎ, এটি শুধু মেমোরি নয়; এটি নিজেই ছোট একটি কম্পিউটার।",
  "## SIM Card-এর ভিতরে কী কী থাকে?",
  "**SIM Card-এর ভিতরে** থাকে—",
  "১. CPU (Microprocessor)",
  "- সব নির্দেশনা (Instruction) প্রক্রিয়া করে।",
  "২. RAM",
  "- অস্থায়ী (Temporary) ডেটা সংরক্ষণ করে।",
  "৩. ROM",
  "- Operating System এবং স্থায়ী নির্দেশনা থাকে।",
  "৪. EEPROM",
  "- এখানে Contacts, SMS, IMSI ইত্যাদি সংরক্ষণ করা হয় এবং প্রয়োজনে আপডেট করা যায়।",
  "## Embedded Operating System",
  "SIM Card-এর নিজের একটি Operating System থাকে।",
  "- এটি নিয়ন্ত্রণ করে—",
  "- কে ডেটা পড়তে পারবে",
  "- কে ডেটা পরিবর্তন করতে পারবে",
  "- কোন Application চলবে",
  "এই কারণেই SIM Card সাধারণ USB Drive-এর মতো নয়।",
  "## File System",
  "SIM Card-এর নিজস্ব File System থাকে।",
  "**এখানে বিভিন্ন ধরনের ফাইল থাকে**, যেমন—",
  "- Contacts",
  "- SMS",
  "- IMSI",
  "- Network Files",
  "- Authentication Files",
  "- Security Researcher-রা ফরেনসিক টুল দিয়ে এই ফাইলগুলো বিশ্লেষণ করেন।",
  "## Security Mechanism",
  "SIM Card-এ শক্তিশালী Security থাকে।",
  "এমনভাবে সুরক্ষা দেওয়া থাকে যাতে সহজে পুরো SIM Card-এর ১:১ কপি (Full Dump) করা না যায়। Access Control List (ACL) ব্যবহার করে নির্ধারণ করা হয় কোন তথ্য পড়া যাবে।",
  "## UICC (Universal Integrated Circuit Card)",
  "UICC হলো আধুনিক প্রজন্মের SIM Card-এর হার্ডওয়্যার প্ল্যাটফর্ম।",
  "অনেকে SIM এবং UICC একই অর্থে ব্যবহার করলেও, আসলে—",
  "- SIM = Application",
  "- UICC = Physical Smart Card Hardware",
  "## USIM কী?",
  "USIM হলো UICC-এর ওপর চলা একটি Application।",
  "বর্তমানে 4G এবং 5G নেটওয়ার্কে USIM ব্যবহৃত হয়।",
  "## GSM এবং CDMA",
  "GSM ফোনে সাধারণ SIM ব্যবহৃত হয়।",
  "CDMA ডিভাইসে R-UIM বা CSIM ব্যবহার হতে পারে, যা একই ধরনের পরিচয়-সংক্রান্ত কাজ করে।",
  "## APDU কী?",
  "APDU (Application Protocol Data Unit) হলো Smart Card-এর সঙ্গে যোগাযোগের স্ট্যান্ডার্ড কমান্ড।",
  "যখন কোনো Forensic Tool  SIM Card থেকে ডেটা পড়ে, তখন APDU Command ব্যবহার করে।",
  "উদাহরণ:",
  "- Read File",
  "- Verify PIN",
  "- Select File",
  "- Get Response",
  "## SIM Card-এর Pinout",
  "SIM Card-এর সোনালি অংশের প্রতিটি পিনের নির্দিষ্ট কাজ আছে।",
  "| Pin | কাজ                       |",
  "| --- | ------------------------- |",
  "| C1  | VCC (Power Supply)        |",
  "| C2  | Reset                     |",
  "| C3  | Clock                     |",
  "| C4  | Reserved                  |",
  "| C5  | Ground (GND)              |",
  "| C6  | Programming Voltage (VPP) |",
  "| C7  | Input/Output (I/O)        |",
  "| C8  | Reserved                  |",
  "## গুরুত্বপূর্ণ Pin-এর কাজ",
  "C1 – VCC",
  "- SIM Card-এ বিদ্যুৎ সরবরাহ করে।",
  "C2 – Reset",
  "- SIM Card পুনরায় চালু (Reset) করতে ব্যবহৃত হয়।",
  "C3 – Clock",
  "- CPU-কে Clock Signal দেয়।",
  "C5 – Ground",
  "- Electrical Ground।",
  "C6 – VPP",
  "- পুরোনো SIM Card Program বা Memory Erase করতে ব্যবহৃত হতো।",
  "C7 – I/O",
  "- SIM Card এবং ফোন/Reader-এর মধ্যে Data আদান-প্রদান হয়।",
  "## Security Researcher হিসেবে কেন এগুলো গুরুত্বপূর্ণ?",
  "- একজন Mobile Forensics বা Security Researcher হিসেবে এই ধারণাগুলো কাজে লাগে—",
  "- SIM Card-এর আর্কিটেকচার বোঝার জন্য।",
  "- SIM Reader দিয়ে নিরাপদভাবে ডেটা সংগ্রহ করার জন্য।",
  "- APDU Command ব্যবহার করে ফরেনসিক বিশ্লেষণ করার জন্য।",
  "- PIN Lock, File System এবং Security Mechanism বোঝার জন্য।",
  "- SIM Cloning ও SIM Authentication কীভাবে কাজ করে তা বিশ্লেষণ করার জন্য।",
  "## ইন্টারভিউতে মনে রাখার বিষয়",
  "- SIM Card একটি Smart Card।",
  "- UICC হলো আধুনিক SIM Card-এর হার্ডওয়্যার প্ল্যাটফর্ম।",
  "- USIM হলো UICC-এর ওপর চলা Application।",
  "- SIM Card-এর ভিতরে CPU, RAM, ROM, EEPROM এবং Operating System থাকে।",
  "- APDU Command দিয়ে Smart Card-এর সঙ্গে যোগাযোগ করা হয়।",
  "C1 = Power, C5 = Ground, C7 = Data (I/O)।",
  "##=============part 4=======",
  "## Standard SIM Formats and Embedded SIM Cards (বাংলায়)",
  "এই অধ্যায়ে মূলত আলোচনা করা হয়েছে:",
  "SIM Card-এর বিভিন্ন আকার (Formats)",
  "- eSIM কী",
  "- iSIM কী",
  "- এগুলোর ব্যবহার",
  "- Mobile Forensics-এ এগুলোর গুরুত্ব",
  "## SIM Card-এর বিভিন্ন Format",
  "প্রযুক্তির উন্নতির সাথে সাথে SIM Card-এর আকার ছোট হয়েছে, কিন্তু এর মূল কাজ একই রয়েছে।",
  "**১. Full-size SIM**",
  "- এটি সবচেয়ে বড় SIM Format।",
  "- আকারে একটি Credit Card-এর মতো।",
  "- বর্তমান মোবাইলে এটি ব্যবহার হয় না।",
  "মূলত পুরোনো GSM System এবং Testing-এর জন্য ব্যবহৃত হতো।",
  "অনেক Chip-enabled Credit Card-এও একই ধরনের Smart Card প্রযুক্তি ব্যবহৃত হয়।",
  "## Contactless Payment কি SIM দিয়ে হয়?",
  "- না।",
  "অনেকেই মনে করেন ব্যাংকের Contactless Card-এ SIM থাকে।",
  "Touch-to-Pay বা Contactless Payment NFC (Near Field Communication) ব্যবহার করে, SIM Card ব্যবহার করে না।",
  "**২. Mini SIM**",
  "- এটিকেই অনেক সময় Standard SIM বলা হয়।",
  "বৈশিষ্ট্য:",
  "- ২০০৪ সালে জনপ্রিয় হয়।",
  "পুরোনো Smartphone এবং Feature Phone-এ ব্যবহৃত হতো।",
  "**৩. Nano SIM**",
  "বর্তমান সময়ে সবচেয়ে বেশি ব্যবহৃত Physical SIM Format।",
  "বৈশিষ্ট্য:",
  "- ২০১২ সালে চালু হয়।",
  "- আধুনিক Smartphone-এ ব্যবহৃত হয়।",
  "Mini SIM-এর তুলনায় অনেক ছোট।",
  "**৪. eSIM (Embedded SIM)**",
  "eSIM হলো এমন একটি SIM যা ফোনের ভেতরে স্থায়ীভাবে লাগানো থাকে।",
  "এটি বের করা যায় না।",
  "এতে Physical SIM Slot-এর প্রয়োজন হয় না।",
  "## eSIM কীভাবে কাজ করে?",
  "আপনি SIM খুলে লাগাবেন না।",
  "বরং Carrier-এর Profile Download করে সক্রিয় করবেন।",
  "উদাহরণ:",
  "- QR Code Scan",
  "- Carrier Activation",
  "- Remote Provisioning",
  "## কোথায় eSIM ব্যবহৃত হয়?",
  "- Apple Watch",
  "- iPad (2nd Generation এবং পরবর্তী কিছু মডেল)",
  "- Google Pixel 2 (Project Fi)",
  "- IoT Device",
  "- Smart Car",
  "- GPS Device",
  "## iPhone-এ eSIM",
  "iPhone-এ eSIM ব্যবহার করতে iOS 12.1 বা তার পরবর্তী সংস্করণ প্রয়োজন।",
  "## Security Researcher হিসেবে eSIM কেন গুরুত্বপূর্ণ?",
  "- eSIM ফোন থেকে খুলে নেওয়া যায় না।",
  "- ফলে Investigation-এর সময়—",
  "- Physical SIM Evidence নাও থাকতে পারে।",
  "- Device থেকেই Data Extract করতে হতে পারে।",
  "- Carrier Profile বিশ্লেষণ করতে হতে পারে।",
  "- এটি ফরেনসিক তদন্তকে কিছু ক্ষেত্রে আরও জটিল করে তোলে।",
  "## IoT Device",
  "eSIM অনেক IoT Device-এ ব্যবহৃত হয়।",
  "উদাহরণ:",
  "- Smart Car",
  "- GPS Tracker",
  "- Smart Meter",
  "- Industrial Sensor",
  "- Wearable Device",
  "## iSIM (Integrated SIM)",
  "iSIM হলো আরও আধুনিক প্রযুক্তি।",
  "এখানে আলাদা SIM Chip থাকে না।",
  "SIM-এর কার্যক্ষমতা Device-এর Main Processor (SoC)-এর মধ্যেই যুক্ত থাকে।",
  "## iSIM-এর সুবিধা",
  "- Device আরও ছোট করা যায়।",
  "- কম বিদ্যুৎ খরচ হয়।",
  "- IoT Device-এর জন্য আদর্শ।",
  "- আলাদা SIM Chip-এর প্রয়োজন হয় না।",
  "## eSIM বনাম iSIM",
  "| eSIM                                     | iSIM                                      |",
  "| ---------------------------------------- | ----------------------------------------- |",
  "| আলাদা Chip থাকে                          | আলাদা Chip থাকে না                        |",
  "| Motherboard-এ স্থায়ীভাবে লাগানো         | Processor-এর ভেতরেই থাকে                  |",
  "| Software দিয়ে Profile পরিবর্তন করা যায় | Processor-এর অংশ হওয়ায় আরও সমন্বিত      |",
  "| Smartphone-এ বেশি ব্যবহৃত                | IoT ও ভবিষ্যতের ছোট ডিভাইসে বেশি সম্ভাবনা |",
  "## একজন Mobile Forensics Investigator কীভাবে দেখবেন?",
  "তদন্তের সময় প্রথমে বুঝতে হবে—",
  "- Physical SIM আছে?",
  "- eSIM আছে?",
  "- Dual SIM?",
  "- eSIM + Physical SIM?",
  "- iSIM-ভিত্তিক Device?",
  "কারণ Data Extraction-এর পদ্ধতি এগুলোর ওপর নির্ভর করে।",
  "## ইন্টারভিউতে মনে রাখার বিষয়",
  "- **Full-size SIM** = Credit Card আকারের পুরোনো Smart Card।",
  "- **Mini SIM** = একসময়ের Standard SIM।",
  "- **Nano SIM** = বর্তমানে সবচেয়ে বেশি ব্যবহৃত Physical SIM।",
  "- **eSIM** = Device-এর ভেতরে স্থায়ীভাবে লাগানো, খুলে फेलা याय ना।",
  "- **iSIM** = Processor-এর মধ্যেই SIM Function যুক্ত থাকে।",
  "- **Contactless Payment (Tap-to-Pay)** = NFC ব্যবহার করে, SIM Card নয়।",
  "> ধন্যবাদ। শীঘ্রই পরবর্তী অংশ (Part 5&6) নিয়ে আসছি।",
    ],
  },
  {
    id: 'blog-5',
    title: 'SIM Forensics A to Z in bangla: Investigating Mobile SIM Cards Part 5&6',
    excerpt: 'Basic to advanced techniques for extracting and analyzing data from mobile SIM cards, including IMSI, ICCID, and call logs.',
    date: 'july 2026',
    readTime: '15 min read',
    tags: ['SIM Forensics', 'Mobile Security'],
    slug: 'sim-forensics-a-to-z-part-5-6',
    content: [
       "==============part 5===================",
  "## SIM Application কী?",
  "SIM Card-এর ভিতরে শুধু হার্ডওয়্যার থাকে না; সেখানে Application-ও থাকে।",
  "এই Application-ই ফোন এবং SIM Card-এর মধ্যে যোগাযোগ (Communication) করায়।",
  "সহজভাবে:",
  "- Phone",
  "- │",
  "- SIM Application",
  "- │",
  "- SIM Hardware",
  "অর্থাৎ, Phone সরাসরি SIM Chip-এর সঙ্গে কথা বলে না; SIM Application-এর মাধ্যমে তথ্য আদান-প্রদান করে।",
  "## কেন SIM Application দরকার?",
  "প্রতিটি Mobile Network এক ধরনের Protocol ব্যবহার করে না।",
  "যেমন—",
  "- GSM Network",
  "- UMTS Network",
  "এগুলোর যোগাযোগের নিয়ম (Protocol) আলাদা হতে পারে।",
  "তাই SIM Application-কে একাধিক Protocol সমর্থন করতে হয়।",
  "যদি কোনো Application শুধু GSM সমর্থন করে, তাহলে সেটি UMTS নেটওয়ার্কে ঠিকমতো কাজ করবে না।",
  "## একজন SIM Application Developer কী করেন?",
  "যারা SIM Application তৈরি করেন, তাদের নিশ্চিত করতে হয় যে সফটওয়্যারটি বিভিন্ন ধরনের SIM Card এবং Network Protocol সমর্থন করে।",
  "নইলে Application শুধুমাত্র একটি নির্দিষ্ট ধরনের SIM-এর সঙ্গেই কাজ করবে।",
  "## GSM Network-এর জন্য কোন Application লাগে?",
  "GSM Network ব্যবহার করতে হলে SIM Application থাকতে হবে।",
  "## UMTS Network-এর জন্য কোন Application লাগে?",
  "UMTS (3G) Network ব্যবহার করতে হলে USIM Application থাকতে হবে।",
  "## SIM বনাম USIM",
  "| SIM Application     | USIM Application                |",
  "| ------------------- | ------------------------------- |",
  "| GSM Network-এর জন্য | UMTS (3G) Network-এর জন্য       |",
  "| পুরোনো প্রযুক্তি    | নতুন ও বেশি নিরাপদ              |",
  "| সীমিত সুবিধা        | উন্নত Authentication ও Security |",
  "## Contact Storage",
  "SIM এবং USIM—দুটোতেই Contact সংরক্ষণ করার সুবিধা থাকে (Abbreviated Dialing Network বা ADN)।",
  "অর্থাৎ, ফোনের কিছু Contacts SIM-এর মধ্যেও সংরক্ষণ করা যেতে পারে।",
  "## Multi-Application UICC",
  "কিছু UICC Card-এ একসঙ্গে SIM Application এবং USIM Application দুটোই থাকে।",
  "ফলে একই কার্ড—",
  "- GSM Network-এও কাজ করতে পারে।",
  "- UMTS Network-এও কাজ করতে পারে।",
  "## কেন দুই সেট Contact দেখা যায়?",
  "Forensic Tool দিয়ে Multi-Application UICC বিশ্লেষণ করলে দেখা যেতে পারে—",
  "- SIM View-এ এক সেট Contact",
  "- USIM View-এ আরেক সেট Contact",
  "কিন্তু বাস্তবে Contact দুটি আলাদা করে সংরক্ষিত থাকে না।",
  "একটি Contact Record-ই থাকে, তবে File ID System-এর মাধ্যমে সেটিকে দুই জায়গা থেকে রেফারেন্স করা হয়।",
  "## Pointer Reference কী?",
  "SIM Card-এ অনেক সময় Data সরাসরি কপি না করে Pointer ব্যবহার করা হয়।",
  "উদাহরণ:",
  "- Actual Contact",
  "- │",
  "- ┌────┴────┐",
  "- │         │",
  "- SIM View ==> USIM View",
  "দুই জায়গায় Contact দেখা গেলেও, প্রকৃত ডেটা একবারই সংরক্ষিত থাকে।",
  "## File System Dump বনাম Logical Dump",
  "এটি Mobile Forensics-এর একটি গুরুত্বপূর্ণ ধারণা।",
  "**১. Logical Dump**",
  "শুধুমাত্র ব্যবহারকারীর জন্য দৃশ্যমান ডেটা সংগ্রহ করে।",
  "- Contacts",
  "- SMS",
  "- Call Information",
  "**২. File System Dump**",
  "পুরো File System বিশ্লেষণ করে।",
  "- Hidden File",
  "- Pointer",
  "- Metadata",
  "- Internal Structure",
  "File System Dump অনেক সময় Logical Dump-এর চেয়ে বেশি তথ্য দিতে পারে।",
  "## কেন এটি Security Researcher-এর জন্য গুরুত্বপূর্ণ?",
  "একজন Mobile Forensics Investigator যদি শুধু Logical Dump নেন, তাহলে কিছু গুরুত্বপূর্ণ তথ্য বাদ পড়তে পারে।",
  "কিন্তু File System Dump করলে—",
  "- Hidden Metadata",
  "- File Structure",
  "- Pointer Reference",
  "- অতিরিক্ত SIM সম্পর্কিত তথ্য",
  "পাওয়ার সম্ভাবনা বেশি।",
  "বর্তমানে এমন File Dump করার টুল খুব সীমিত।",
  "## ইন্টারভিউতে মনে রাখার বিষয়",
  "- **SIM Application** = GSM Network-এর জন্য ব্যবহৃত Application।",
  "- **USIM Application** = UMTS (3G) Network-এর জন্য ব্যবহৃত Application।",
  "- **একটি UICC Card-এ** একাধিক Application থাকতে পারে।",
  "- **একই Contact দুই View-তে** দেখা গেলেও, ডেটা একবারই সংরক্ষিত থাকতে পারে।",
  "- **File System Dump সাধারণত** Logical Dump-এর তুলনায় বেশি তথ্য দেয়।",
  "===========Part 6=======================",
  "## Integrated Circuit Card Identifier (ICCID)",
  "এই অধ্যায়ে শেখানো হয়েছে—",
  "- ICCID কী",
  "- ICCID-এর প্রতিটি অংশের অর্থ",
  "- কীভাবে ICCID পড়তে হয়",
  "- Nibble Swap কী",
  "- ফরেনসিক তদন্তে ICCID কেন গুরুত্বপূর্ণ",
  "## ICCID কী?",
  "ICCID (Integrated Circuit Card Identifier) হলো একটি SIM Card-এর ইউনিক সিরিয়াল নম্বর।",
  "এটি প্রতিটি SIM Card-এর জন্য আলাদা (Unique) হয়।",
  "যেমন প্রত্যেক মানুষের National ID আলাদা, তেমনি প্রতিটি SIM-এর ICCID-ও আলাদা।",
  "ICCID সাধারণত SIM Card-এর গায়ে প্রিন্ট করা থাকে এবং UICC-এর (SIM Card) ভেতরেও সংরক্ষিত থাকে।",
  "## ICCID কেন দরকার?",
  "Mobile Network Operator (Carrier) ICCID ব্যবহার করে—",
  "- SIM Card শনাক্ত করতে।",
  "- SIM Activate করতে।",
  "- SIM Replace করতে।",
  "- Authentication এবং Diagnostic কাজে।",
  "## ICCID কত সংখ্যার হয়?",
  "সাধারণত ১৯ বা ২০ ডিজিটের হয়।",
  "উদাহরণ:",
  "- 8988012345678901234",
  "## ICCID-এর গঠন (Breakdown)",
  "ICCID কয়েকটি অংশ নিয়ে গঠিত:",
  "- ICCID",
  "- │",
  "- ├── System Code",
  "- ├── Country Code",
  "- ├── Issuer Identifier",
  "- ├── Unique Identifier",
  "- └── Checksum",
  "## ১. System Code",
  "SIM Card-এর জন্য System Code = 89",
  "এর অর্থ হলো—",
  "- এই Card একটি Telecommunication SIM Card।",
  "অর্থাৎ ICCID যদি 89 দিয়ে শুরু হয়, তাহলে বোঝা যায় এটি Telecom Industry-এর SIM।",
  "## ২. Country Code",
  "এরপর থাকে Country Code।",
  "উদাহরণ:",
  "- 1 = USA/Canada",
  "- 44 = United Kingdom",
  "- 880 = Bangladesh (টেলিফোন Country Code)",
  "এই অংশ দেখে SIM কোন দেশের জন্য ইস্যু হয়েছে তা বোঝা যায়।",
  "## ৩. Issuer Identifier Number (IIN)",
  "এটি Carrier বা Mobile Operator-কে চিহ্নিত করে।",
  "উদাহরণ:",
  "- Grameenphone",
  "- Robi",
  "- Banglalink",
  "- Airtel",
  "- AT&T",
  "- Verizon",
  "প্রতিটি অপারেটরের আলাদা Issuer Identifier থাকে।",
  "## ৪. Unique Identifier",
  "এই অংশটি নির্দিষ্ট SIM Card-কে অন্য সব SIM থেকে আলাদা করে।",
  "অর্থাৎ একই অপারেটরের দুইটি SIM হলেও তাদের Unique Identifier এক হবে না।",
  "## ৫. Checksum",
  "সবশেষে থাকে Checksum।",
  "এটি Luhn Algorithm ব্যবহার করে তৈরি করা হয়।",
  "এর কাজ হলো—",
  "- ICCID ভুল লেখা হয়েছে কি না যাচাই করা।",
  "- Data Corruption হয়েছে কি না পরীক্ষা করা।",
  "একই Algorithm Credit Card Number যাচাই করতেও ব্যবহৃত হয়।",
  "## যদি ICCID ১৯ ডিজিটের হয়?",
  "যদি ICCID ২০-এর বদলে ১৯ ডিজিটের হয়, তাহলে শেষে 'F' যোগ করা হয়, যা একটি Null Character হিসেবে ব্যবহৃত হয়।",
  "## Nibble Swap কী?",
  "এটি Mobile Forensics-এর একটি গুরুত্বপূর্ণ বিষয়।",
  "SIM Card-এর ভেতরে ICCID অনেক সময় স্বাভাবিকভাবে সংরক্ষিত থাকে না।",
  "এটি Nibble Swap Order-এ সংরক্ষিত হয়।",
  "অর্থাৎ,",
  "- দুইটি করে সংখ্যা জোড়া বানিয়ে তাদের অবস্থান উল্টে দেওয়া হয়।",
  "উদাহরণ",
  "**ধরা যাক**,",
  "- 89 12 34 56",
  "**Nibble Swap হলে হবে—**",
  "- 98 21 43 65",
  "Forensic Tool এই Swap হওয়া ডেটাকে আবার সঠিক ক্রমে রূপান্তর করে।",
  "## PIN Lock থাকলেও ICCID পড়া যায়?",
  "- হ্যাঁ।",
  "ফোন PIN Lock থাকলেও ICCID পড়া সম্ভব।",
  "কারণ ফোন বা External SIM Reader-এর ICCID পড়ার অনুমতি থাকে।",
  "## iPhone-এ ICCID কোথায় দেখা যায়?",
  "iPhone-এ:",
  "- Settings → General → About → Primary → ICCID",
  "এখানে ICCID দেখা যায়।",
  "## একজন Security Researcher-এর জন্য ICCID কেন গুরুত্বপূর্ণ?",
  "Mobile Forensics-এ ICCID ব্যবহার করে—",
  "- SIM Card শনাক্ত করা।",
  "- কোন দেশের SIM তা জানা।",
  "- কোন Carrier-এর SIM তা নির্ধারণ করা।",
  "- SIM বদলানো হয়েছে কি না যাচাই করা।",
  "- SIM Swap Fraud তদন্তে প্রমাণ সংগ্রহ করা।",
  "- Device এবং SIM-এর সম্পর্ক বিশ্লেষণ করা।",
  "## ICCID বনাম IMSI",
  "| ICCID                     | IMSI                                        |",
  "| ------------------------- | ------------------------------------------- |",
  "| SIM Card-এর Serial Number | Subscriber-এর Identity Number               |",
  "| SIM Card শনাক্ত করে       | মোবাইল ব্যবহারকারীকে নেটওয়ার্কে শনাক্ত করে |",
  "| SIM-এর গায়ে লেখা থাকে    | সাধারণত SIM-এর ভেতরে সংরক্ষিত থাকে          |",
  "| পরিবর্তন হয় না           | নেটওয়ার্কের পরিচয়ের সঙ্গে সম্পর্কিত       |",
  "## ইন্টারভিউতে মনে রাখার বিষয়",
  "- **ICCID** = SIM Card-এর ইউনিক Serial Number।",
  "- **সব SIM-এর** ICCID আলাদা।",
  "- **ICCID** সাধারণত ১৯–২০ ডিজিটের হয়।",
  "- **89** = Telecom System Code।",
  "- **Country Code** থেকে SIM-এর দেশ জানা যায়।",
  "- **Issuer Identifier** থেকে Carrier জানা যায়।",
  "- **Checksum** = Luhn Algorithm দিয়ে যাচাই করা হয়।",
  "- **SIM-এর ভেতরে** ICCID অনেক সময় Nibble Swap Format-এ সংরক্ষিত থাকে।",
  "- **PIN Lock** থাকলেও ICCID পড়া সম্ভব।",

    ],
  },
];

export const terminalCommands: Record<string, string[]> = {
  whoami: ['Cyber Security Engineer'],
  help: [
    'Available commands:',
    '  whoami     - display current user role',
    '  skills     - list core skill areas',
    '  projects   - jump to projects section',
    '  contact    - jump to contact section',
    '  clear      - clear the terminal',
  ],
  skills: [
    'Programming   : Python, Bash, JavaScript, PHP, SQL, Rust',
    'Security      : Web Pentesting, API Security, Network Security, OSINT',
    'Tools         : Burp Suite, Nmap, Metasploit, Wireshark, SQLMap, more...',
  ],
};
